# Blog info
blog_name: EyreFree
slogan: This is the way the world ends, not with a bang, but a whimper.
url: http://www.eyrefree.org

# Set avatar (Absolute url and relative url)
avatar: https://avatars.githubusercontent.com/u/10757132

# Set favicon
favicon: /favicon.ico

# For seo
keywords: EyreFree,Swift

home_nav:
  - name: åšå®¢
    url: /archives
    target: _blank
  # - name: æ˜é‡‘
  #   url: https://juejin.im/user/58e106a12f301e0062127340
  #   target: _blank
  - name: å¾®åš
    url: https://weibo.com/eyrefree777
    target: _blank
  - name: Twitter
    url: https://twitter.com/EyreFree777
    target: _blank
  # - name: ç®€ä¹¦
  #   url: http://www.jianshu.com/users/e4d1f69048ea
  #   target: _blank
  # - name: Coding
  #   url: https://coding.net/u/eyrefree
  #   target: _blank
  # - name: GitHub
  #   url: http://github.com/eyrefree
  #   target: _blank
  # - name: LeetCode
  #   url: https://leetcode-cn.com/u/eyrefree/
  #   target: _blank
  # - name: LinkedIn
  #   url: http://www.linkedin.com/in/eyrefree
  #   target: _blank
  # - name: ç®€å†
  #   url: http://resume.eyrefree.org/
  #   target: _blank
  - name: V2EX
    url: http://v2ex.com/member/eyrefree
    target: _blank
  # - name: CSDN
  #   url: http://my.csdn.net/EyreFree
  #   target: _blank
  # - name: Steam
  #   url: http://steamcommunity.com/id/EyreFree
  #   target: _blank
  # - name: Battle.net
  #   url: http://d3.blizzard.cn/profile/EyreFree-5717/478027
  #   target: _blank
  # - name: è‹ICPå¤‡15023694å·-1
  #   url: http://beian.miit.gov.cn
  #   target: _blank

# config page nav
page_nav:
  - name: åšå®¢
    url: /archives/
    target_blank: false # ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: åˆ†ç±»
    url: /category/
    target_blank: false
  - name: æ ‡ç­¾
    url: /tag/
    target_blank: false
  - name: é¡¹ç›®
    url: /project/
    target_blank: false
  - name: å‹é“¾
    url: /link/
    target_blank: false
  - name: å…³äº
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: æœç´¢
    url: /search/
    target_blank: false

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# é¢åŒ…å±‘
breadcrumb:
  isShow: true # true|fase

# ç›’å­
toolbox:
  isShow: true # true|fase
  text: ç›’å­

search_slogan:
  isShow: true # true|fase
  text: äººç”Ÿæ€»æ˜¯ç»“æŸäºå¯»æ‰¾å‡ºè·¯çš„è¿‡ç¨‹ä¸­ã€‚

link_slogan:
  isShow: true # true|fase
  text: äº¤æ¢å‹é“¾å¯å‘é€é‚®ä»¶è‡³ eyrefree@eyrefree.org


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: æ”¯æŒä¸€ä¸‹
  tip: ğŸš€ ç»™ EF åˆ·ç«ç®­ ğŸš€
  items:
    - type: å¾®ä¿¡
      text: å¾®ä¿¡æ‰«ä¸€æ‰«
      imgUrl: /WeChat.png
    - type: æ”¯ä»˜å®
      text: æ”¯ä»˜å®æ‰«ä¸€æ‰«
      imgUrl: /AliPay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# ä¸ªæ€§åŒ–è®¾ç½®
# =========================================================

# Custom CSS style, æ¨èæŠŠæ ·å¼æ–‡ä»¶æ”¾åœ¨blogæºç æ–‡ä»¶å¤¹ï¼Œè€Œä¸æ˜¯ä¸»é¢˜é‡Œé¢
personal_style: /css/personal-style.css

# è¿™ä¸ªå€¼å–å†³äºä½ å¾—èƒŒæ™¯å›¾ç‰‡æ˜¯æ·±è‰²è¿˜æ˜¯æµ…è‰²ï¼Œæ·±è‰²ç”¨darkï¼Œæµ…è‰²ç”¨light
home_background_scheme: light # darkã€light

# custom font-family æš‚æ—¶åªæ”¯æŒè¿™3ç§è‹±æ–‡å­—ä½“ï¼Œä½ å¯ä»¥å®Œå…¨è‡ªå®šä¹‰å­—ä½“(çœ‹æ–‡æ¡£)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# ç¬¬ä¸‰æ–¹æœåŠ¡
# =========================================================
# Stats
#google_analytics: UA-74357398-1
baidu_analytics: 638f7245dab1e13e3d8fbdd9cc3b0895

# Comment service

disqus_shortname: eyrefree
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#æœ‰è¨€ç”¨æˆ·ç¼–å·
# uyan_key:

# ç•…è¨€, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  è¿™é‡Œå¼€å¯
  changyan_appid:
  changyan_appkey:

# gitalkè¯„è®ºç»„ä»¶ï¼ŒæŠŠä¸‹é¢çš„é…ç½®æ¢æˆä½ çš„ï¼Œå®˜æ–¹æ–‡æ¡£: https://gitalk.github.io/
gitalk:
  enable: false # å¦‚æœä½¿ç”¨ gitalkï¼Œè¯·è®¾ç½®æ”¹ä¹‹ä¸ºtrue
  clientID: 277317290454635afa73
  clientSecret: 78223c859304da5e8d71bfce136d436c6ff95c37
  repo: blog-comment
  owner: forsigner
  admin: forsigner


# gitment comment service
gitment:
  enable: false  # true | false  è¿™é‡Œå¼€å¯
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # å¦‚æœä½¿ç”¨valineï¼Œè¯·è®¾ç½®æ”¹ä¹‹ä¸ºtrue
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# ä¸ç®—å­,æ–‡ç« è®¿é—®é‡ç»Ÿè®¡å’Œæ˜¾ç¤º
busuanzi: true

# åº•éƒ¨é¡µè„š
footer:
  beian: "è‹ICPå¤‡15023694å·-1"

# =========================================================
# é¡µé¢å†…å®¹è®¾ç½®
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "ä¸€ä¸ªè„±ç¦»äº†é«˜çº§è¶£å‘³çš„äººã€‚"
    - "A man interested in coding."
  # - type: qq
  #   icon: icon-qq
  #   text_key: QQ
  #   text_value: "1795179491"
  #   text_value_url: http://wpa.qq.com/msgrd?v=3&uin=1795179491&site=qq&menu=yes
  # - type: weibo
  #   icon: icon-weibo
  #   text_key: å¾®åš
  #   text_value: "EyreFree"
  #   text_value_url: http://weibo.com/eyrefree777
  # - type: twitter
  #   icon: icon-twitter
  #   text_key: æ¨ç‰¹
  #   text_value: "EyreFree777"
  #   text_value_url: https://twitter.com/EyreFree777
  # - type: info
  #   icon: icon-info
  #   text_key: å¤‡æ¡ˆ
  #   text_value: "è‹ICPå¤‡15023694å·-1"
  #   text_value_url: http://www.miitbeian.gov.cn/state/outPortal/loginPortal.action
  - type: github
    icon: icon-github
    text_key: GitHub
    text_value: EyreFree
    text_value_url: http://github.com/EyreFree
  - type: leetcode
    icon: icon-info
    text_key: LeetCode
    text_value: EyreFree
    text_value_url: https://leetcode-cn.com/u/eyrefree/
  - type: steam
    icon: icon-info
    text_key: Steam
    text_value: EyreFree
    text_value_url: http://steamcommunity.com/id/EyreFree
  - type: mail
    icon: icon-mail
    text_key: é‚®ç®±
    text_value: "eyrefree@eyrefree.org"
    text_value_url: mailto:eyrefree@eyrefree.org
  - type: location
    icon: icon-location
    text_key: ä½ç½®
    text_value: "æ— é”¡"
    text_value_url: "https://map.baidu.com/search/%E6%97%A0%E9%94%A1%E5%B8%82"

link:
  - name: TimothyQiu's Blog
    info: Hi, this is Timothy Qiu. I'm a new programmer.
    url: http://timothyqiu.com/
    avatar: https://avatars.githubusercontent.com/u/372476?v=4
  - name: ä½³ä½³é…±
    info: è·¨æ¬¡å…ƒæ—¥å¸¸å–èŒ
    url: https://luojia.me/
    avatar: https://avatars.githubusercontent.com/u/4150781?v=4
  - name: åœåœå£
    info: å‰ç«¯å¼€å‘ã€äººåƒå†™çœŸ
    url: http://mouto.org
    avatar: https://avatars0.githubusercontent.com/u/1933673?s=460&v=4
  - name: ä¸€ç¼•æ®‡æµåŒ–éšåŠè¾¹å†°éœœ
    info: åœ¨æ¯ä¸€ä¸ªè‹¦æ€å†¥æƒ³çš„ç¬é—´æ±‚çŸ¥
    url: https://halfrost.com/
    avatar: https://avatars0.githubusercontent.com/u/10825609?v=3&s=460
  - name: Sunnyyoung
    info: iOS / macOS å¼€å‘è€…ã€å¼€æºçˆ±å¥½è€…ã€ä¸“ä¸šé€†å‘å¼€å‘ï¼Œå…¨æ ˆï¼Œå•¥éƒ½ä¼š
    url: https://www.sunnyyoung.net/
    avatar: https://avatars2.githubusercontent.com/u/5926284?s=460&v=4


project:
  - type: personal
    name: EFQRCode
    url: https://www.efqrcode.com
    intro: iOS è‰ºæœ¯äºŒç»´ç ç”Ÿæˆ
  - type: personal
    name: EFIconFont
    url: https://github.com/EFPrefix/EFIconFont
    intro: ä¸€ä¸ª Swift å®ç°çš„æ™®é€šçš„ IconFont å°è£…
